import Checkbox from "../Checkbox";
import FreqInput from "../FreqInput";
import NumberInput from "../NumberInput";
import Button from "../Button";
import MenuOptions from "../MenuOptions";
import "./index.scss";
import { useState } from "react";
import {
  OptionType,
  AllowedScales,
  SynthOscType,
  ExerciseOptions,
} from "../../common/types";

// TODO: right now the options are hard-coded. Refactor so that they can be generated by the options argument

interface Props {
  options: ExerciseOptions;
  error: string;
  handleSubmit: (e: React.FormEvent<HTMLFormElement>) => void;
  handleMenuSelectChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  handleCheckboxChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleNumInputChange: (id: string, v: number) => void;
  reset: () => void;
}

const ExerciseSetUp = ({
  options,
  error,
  handleSubmit,
  handleMenuSelectChange,
  handleCheckboxChange,
  handleNumInputChange,
  reset,
}: Props) => {
  const [numQuestionsIsDisabled, setNumQuestionsIsDisabled] = useState(true);

  return (
    <form className="exercise-set-up" method="post" onSubmit={handleSubmit}>
      <div>
        <h2>Select a sound:</h2>
        <MenuOptions
          defaultOption={SynthOscType.TRIANGLE}
          id={OptionType.OSCTYPE}
          onChange={handleMenuSelectChange}
        >
          {Object.values(SynthOscType)}
        </MenuOptions>
      </div>
      <div>
        <h2>Select a scale:</h2>
        <MenuOptions
          defaultOption={AllowedScales.EDO_24}
          id={OptionType.SCALENAME}
          onChange={handleMenuSelectChange}
        >
          {Object.values(AllowedScales)}
        </MenuOptions>
      </div>
      <div>
        <h2>Include intervals…</h2>
        <Checkbox
          id={OptionType.SMALLERTHANEQUAVE}
          initValue={true}
          onChange={handleCheckboxChange}
        >
          smaller than an equave
        </Checkbox>
        <Checkbox
          id={OptionType.LARGERTHANEQUAVE}
          initValue={false}
          onChange={handleCheckboxChange}
        >
          larger than an equave
        </Checkbox>
      </div>
      <div>
        <h2>Play intervals…</h2>
        <Checkbox
          id={OptionType.PLAYARP}
          initValue={true}
          onChange={handleCheckboxChange}
        >
          as arpeggios
        </Checkbox>
        <Checkbox
          id={OptionType.PLAYSIM}
          initValue={true}
          onChange={handleCheckboxChange}
        >
          simultaneously
        </Checkbox>
      </div>

      <div>
        <h2>Range (in Hz)</h2>
        <div>
          <FreqInput
            id={OptionType.MINFREQ}
            freq={options.minFreq.v}
            onChange={handleNumInputChange}
          >
            from
          </FreqInput>
          <FreqInput
            id={OptionType.MAXFREQ}
            freq={options.maxFreq.v}
            onChange={handleNumInputChange}
          >
            to
          </FreqInput>
        </div>
      </div>
      <div>
        <h2>How many questions?</h2>
        <NumberInput
          className={OptionType.NUMQUESTIONS}
          disabled={numQuestionsIsDisabled}
          id={OptionType.NUMQUESTIONS}
          value={options.numQuestions.v}
          onChange={handleNumInputChange}
        ></NumberInput>
        <Checkbox
          id={OptionType.INFINITEMODE}
          initValue={true}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            handleCheckboxChange(e);
            setNumQuestionsIsDisabled(e.target.checked);
          }}
        >
          infinite mode
        </Checkbox>
      </div>

      <Button type="button" onClick={reset}>
        restore default
      </Button>
      <Button type="submit">start</Button>

      <p>{error}</p>
    </form>
  );
};

export default ExerciseSetUp;
